name: jenkins

services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins
    restart: always
    ports:
      - 8080:8080
    volumes:
      - jenkins_home:/var/jenkins_home

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    container_name: grafana
    image: grafana/grafana
    restart: always
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  jenkins_home: {}
  grafana-storage: {}